services:
  user-service:
    build: Services/UserService
    container_name: user_service
    ports:
      - "8000:8000"
    networks:
      - obstarace-net
    env_file:
      - .env
    environment:
      - USER_DATABASE_URL=${USER_DATABASE_URL}
    depends_on:
      user-db:
        condition: service_healthy

  user-db:
    image: postgres:16
    container_name: user_db
    networks:
      - obstarace-net
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USER_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${USER_DATABASE_PASSWORD}
      - POSTGRES_DB=${USER_DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DATABASE_USERNAME} -d ${USER_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  race-service:
    build: Services/RaceService
    container_name: race_service
    ports:
      - "8001:8001"
    networks:
      - obstarace-net
    env_file:
      - .env
    environment:
      - RACE_DATABASE_URL=${RACE_DATABASE_URL}
      - SECRET_KEY=${USER_SECRET_KEY}
    depends_on:
      race-db:
        condition: service_healthy

  race-db:
    image: postgres:16
    container_name: race_db
    networks:
      - obstarace-net
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${RACE_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${RACE_DATABASE_PASSWORD}
      - POSTGRES_DB=${RACE_DATABASE_NAME}
    ports:
      - "5434:5432"
    volumes:
      - race_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${RACE_DATABASE_USERNAME} -d ${RACE_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-service:
    build: Services/PaymentService
    container_name: payment_service
    ports:
      - "8002:8002"
    networks:
      - obstarace-net
    env_file:
      - .env
    environment:
      - PAYMENT_DATABASE_URL=${PAYMENT_DATABASE_URL}
      - SECRET_KEY=${USER_SECRET_KEY}
    depends_on:
      payment-db:
        condition: service_healthy

  payment-db:
    image: postgres:16
    container_name: payment_db
    networks:
      - obstarace-net
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PAYMENT_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${PAYMENT_DATABASE_PASSWORD}
      - POSTGRES_DB=${PAYMENT_DATABASE_NAME}
    ports:
      - "5435:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PAYMENT_DATABASE_USERNAME} -d ${PAYMENT_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe_cli
    command: listen --forward-to payment-service:8002/payments/webhook
    restart: on-failure
    networks:
      - obstarace-net
    environment:
      - STRIPE_API_KEY=${PAYMENT_SECRET_KEY}
    depends_on:
      - payment-service

volumes:
  user_db_data:
  race_db_data:
  payment_db_data:

networks:
  obstarace-net:
    driver: bridge