events {}

http {
    upstream user_service { server user-service:8000; }
    upstream race_service { server race-service:8001; }
    upstream payment_service { server payment-service:8002; }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Cookie $http_cookie;
        }

        location /api/race/ {
            proxy_pass http://race_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/registration/ {
            proxy_pass http://race_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /payments/ {
            proxy_pass http://payment_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}