global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8000']

  - job_name: 'race-service'
    static_configs:
      - targets: ['race-service:8001']

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8002']