"""add track_id to registrations

Revision ID: 1a2a45db9a0e
Revises: 14c62f0891ac
Create Date: 2026-05-30 16:42:57.664493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2a45db9a0e'
down_revision: Union[str, Sequence[str], None] = '14c62f0891ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obstacles', sa.Column('organiser_id', sa.Integer(), nullable=False))
    op.add_column('registrations', sa.Column('track_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_race_participant_track', 'registrations', ['race_id', 'participant_id', 'track_id'])
    op.create_foreign_key(None, 'registrations', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint('uq_race_participant_track', 'registrations', type_='unique')
    op.drop_column('registrations', 'track_id')
    op.drop_column('obstacles', 'organiser_id')
    # ### end Alembic commands ###
