"""unique registration_id on payments

Revision ID: 3816d24bf536
Revises: de36ee56f450
Create Date: 2026-06-22 16:48:20.151780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3816d24bf536'
down_revision: Union[str, Sequence[str], None] = 'de36ee56f450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('participant_email', sa.String(length=100), nullable=False))
    op.add_column('payments', sa.Column('participant_name', sa.String(length=100), nullable=False))
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               type_=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatusenum'),
               existing_nullable=False)
    op.create_unique_constraint(None, 'payments', ['registration_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatusenum'),
               type_=postgresql.ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='paymentstatus'),
               existing_nullable=False)
    op.drop_column('payments', 'participant_name')
    op.drop_column('payments', 'participant_email')
    # ### end Alembic commands ###
