"""add checkout_url to payment

Revision ID: de36ee56f450
Revises: 446d38354bc0
Create Date: 2026-06-10 22:36:20.376002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de36ee56f450'
down_revision: Union[str, Sequence[str], None] = '446d38354bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('checkout_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'checkout_url')
    # ### end Alembic commands ###
